name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Adjust if you use a different Node.js version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      ##############################
      # Frontend (React)
      ##############################
      - name: Install dependencies (React)
        working-directory: ./viejourney-ui
        run: npm ci

      - name: Build React App
        working-directory: ./viejourney-ui
        run: npm run build

      ##############################
      # Backend (NestJS)
      ##############################
      - name: Install dependencies (NestJS)
        working-directory: ./viejourney-api
        run: npm ci

      - name: Build NestJS App
        working-directory: ./viejourney-api
        run: npm run build

